meta_product_name: "Coin Travaux"
meta_title: "Coin Travaux - Choisir un entrepreneur sera un jeu d'enfant !"
meta_description: "Coin travaux vous met en connection avec des entrepreneurs pour vous accompagner avant l'achat de votre bien, afin d'éviter des vices cachés et pour vos projets de rénovation."
meta_image: "form_picture.jpg" # should exist in `app/assets/images/`
twitter_account: "@lamainabbar"   # required for Twitter Cards
